$(document).ready ->
  $.fn.selectpicker.Constructor.BootstrapVersion = '4';
  $('select').selectpicker({ liveSearch: true })

  $('.proof-link').on 'click', ->
    console.log($('#deed_links'))
    $('#deed_links:last').last().after '<input class="form-control" required="required" multiple="multiple" type="text"  name="deed[links][]" id="deed_links">'
    return
  return

# ---
# generated by js2coffee 2.2.0